---
efi:
  mountPoint: /boot/efi
  recommendedSize: 1024MiB
  minimumSize: 32MiB
  label: EFI
userSwapChoices: [none]
initialSwapChoice: none
initialPartitioningChoice: none
defaultPartitionTableType: gpt
createHybridBootloaderLayout: true
defaultFileSystemType: btrfs
allowManualPartitioning: true
preCheckEncryption: false
luksGeneration: luks2
drawNestedPartitions: false
alwaysShowPartitionLabels: true
essentialMounts: ["live-*", control, ventoy]
lvm:
  enable: false
