#!/bin/sh
set -eu

. /usr/lib/live/config.sh

Cmdline ()
{
    for parameter in ${LIVE_CONFIG_CMDLINE}; do
        case "$parameter" in
            live-config.username=*|username=*)
                LIVE_USERNAME=${parameter#*username=}
                ;;
        esac
    done
}

Init ()
{
    if ! pkg_is_installed miubomz-live-settings || component_was_executed miubomz-software; then
        exit 0
    fi
    printf ' miubomz-software'
}

Config ()
{
    usermod -a -G i2c "$LIVE_USERNAME"
    /usr/lib/miubomz/initialize-user "$LIVE_USERNAME"
    chown -R "$LIVE_USERNAME:$LIVE_USERNAME" /home/linuxbrew/.linuxbrew
    touch /var/lib/live/config/miubomz-software
}

Cmdline
Init
Config
